info:
  name: CUTECH-4147 - Retrieve a list of destination configurations
  type: http
  seq: 6

http:
  method: GET
  url: https://platform.adobe.io/data/core/activation/authoring/destinations
  headers:
    - name: Accept
      value: application/json
    - name: Content-Type
      value: application/json
    - name: x-api-key
      value: "{{AEP_CLIENT_ID}}"
    - name: x-gw-ims-org-id
      value: "{{AEP_IMS_ORG}}"
    - name: x-sandbox-name
      value: "{{AEP_SANDBOX_NAME}}"
  auth: inherit

runtime:
  scripts:
    - type: before-request
      code: |-
        const token = bru.getVar("ACCESS_TOKEN");

        if (!token) {
          throw new Error("ACCESS_TOKEN is not available");
        }

        req.setHeader("Authorization", `Bearer ${token}`);

        console.log("Authorization header set.");

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
